### PR TITLE
Update README and update github actions

### PR DESCRIPTION
**Pull request by ezmiller**
## Goal / Problem

Update the README so it represents more closely what we are doing / hope to do. 

## Solution

A list of changes here:
* Update the version to `1.00-alpha1`. Per our discussion, we will be in `alpha` while we experiment.
* Filled out the README a bit
* Added a github "continuous development" (CD) workflow to test & lint the latest PR. 
* Added a badge  for the status of the CD workflow status
* Added a badge for the latest clojars version (none yet). 

## How to test

Not much to test here. Please read through the README update and check that it's reasonable for the moment. I expect we will update it again very shortly, fillout out the "Usage" section. I think we can make an initial update there after we adjust the library to use the index in TMD.

### CODE REVIEW

**Comment by rsiddharthan** [comment]
README has a exploratory tone - should we make it as a timeseries library for tablecloth, as an objective

**Comment by ezmiller** [comment]
> README has a exploratory tone - should we make it as a timeseries library for tablecloth, as an objective

@rsiddharthan Thank you for taking a look. Can you let me know specific parts of the text that  could have a less exploratory tone?

**Review by rsiddharthan — APPROVED** [review]
Good to go on the README. Now we have placeholders to target

**Comment by ezmiller** [comment]
Thanks @rsiddharthan

**Pull request merged**
